//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickBlocksServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordTable
    {
        public int RecordId { get; set; }
        public int UserId { get; set; }
        public string GameMode { get; set; }
        public int GameScore { get; set; }
        public Nullable<System.DateTime> GameTime { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
